apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: minio-minio-svc
  labels:
    app: minio-minio
    chart: minio-0.3.1
    release: minio
    heritage: Tiller
  annotations:
spec:
  rules:
    - host: minio-minio-svc
      http:
        paths:
          - path: /
            backend:
              serviceName: minio-minio-svc
              servicePort: 9000
