apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "nextcloud.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "4096m"
spec:
  tls:
  - hosts:
    - {{ .Values.proxy.ingress.hostname }}
    secretName: {{ .Values.proxy.ingress.tlssecret }}
  rules:
  - host: {{ .Values.proxy.ingress.hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "nextcloud.fullname" . }}
          servicePort: 80
