apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mariadbpvc.volume.pvcname }}
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: {{ .Values.mariadbpvc.volume.size }}
