apiVersion: v1
kind: Service
metadata:
  name: {{ template "nextcloud.mariadb.fullname" . }}
spec:
  selector:
    app: {{ template "nextcloud.mariadb.fullname" . }}
  ports:
  - name: mariadb
    port: 3306
