apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.nextcloudpvc.volume.pvcname }}
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: {{ .Values.nextcloudpvc.volume.size }}
