# Install MySQL Packages
---
- name: Install MySQL
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ mysql_packages }}"

- name: Create Creds
  template:
    src: creds.cnf.j2
    dest: /root/.my.cnf

- name: Start MariaDB
  service: name=mariadb state=started enabled=yes
